name: expdabk
channels:
  - anaconda
  - vnmabus
  - bioconda/label/cf201901
dependencies:
  - python=3.6
  - notebook=5.7.8
  - numpy=1.16.4
  - scipy=1.2.1
  - pandas=0.24.2
  - matplotlib=3.1.0
  - seaborn=0.9.0
  - scikit-learn=0.21.2
  - dcor=0.3
  - minepy=1.2.3